version: '3.8'

services:
  broker:
    build:
      context: ./../broker-service
      dockerfile: ./../broker-service/broker.dockerfile
    ports:
      - "8080:80"
    deploy:
      mode: replicated
      replicas: 1