services:
  broker:
    build:
      context: ./../broker-service
      dockerfile: ./../broker-service/broker.dockerfile
    ports:
      - "8080:80"
    deploy:
      mode: replicated
      replicas: 1
      
  authentication-service:
    build:
      context: ./../authentication-service
      dockerfile: ./../authentication-service/authentication-service.dockerfile
    ports:
      - "8081:80"
    restart: always  
    deploy:
      mode: replicated
      replicas: 1
    environment:
      DSN: "host=postgres port=5432 user=postgres password=password dbname=users sslmode=disable timezone=UTC connect_timeout=5"
  
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: users
    ports:
      - "5432:5432"
    restart: always  
    volumes:
      - ./db-data/postgres/:/var/lib/postgresql/data
    deploy:
      mode: replicated
      replicas: 1
      